'use strict';
const data=JSON.parse(document.getElementById('data').textContent),$=id=>document.getElementById(id);
const video=$('video'),canvas=$('overlay'),ctx=canvas.getContext('2d');
let clip=null,events=[],selected=null,frameIndex=0;
const percent=v=>Number.isFinite(v)?`${Math.round(v*100)}%`:'Not measured';
const metres=v=>Number.isFinite(v)?`${v>=0?'+':''}${(v*100).toFixed(1)} cm`:'Unknown';
let reviews=[];try{reviews=JSON.parse(localStorage.getItem('vmax-review-log-v1')||'[]');if(!Array.isArray(reviews))reviews=[];}catch(e){reviews=[];}
function list(){ $('clips').replaceChildren();const f=$('filter').value;for(const c of data.clips){const n=c.result?Object.values(c.result.tracks).reduce((a,t)=>a+t.events.length,0):0;if(f==='candidates'&&!n||f==='unprocessed'&&c.result)continue;const b=document.createElement('button');b.className='clip'+(clip?.id===c.id?' active':'');b.textContent=c.id.slice(0,12);const s=document.createElement('small');s.textContent=`${c.split} · ${c.result?n+' candidates':'Not analysed'}`;b.append(s);b.onclick=()=>choose(c);$('clips').append(b);}}
function choose(c){clip=c;selected=null;$('error').textContent='';video.src=c.video;$('download').href=c.video;$('title').textContent=`Clip ${c.id.slice(0,12)}`;$('split').textContent=c.split;$('status').textContent=c.result?'Inspect original footage and estimated geometry.':'Video ready. No model predictions are available for this clip.';$('coverage').textContent=percent(c.result?.evidence?.frames_with_any_car_fraction);events=[];
for(const [tid,t] of Object.entries(c.result?.tracks||{})){for(const [index,e] of t.events.entries())events.push({tid,index,e,t});}
events.sort((a,b)=>a.e.start_frame-b.e.start_frame);$('count').textContent=c.result?events.length:'Not analysed';$('events').replaceChildren();for(const x of events){const b=document.createElement('button');b.className='event';b.textContent=`${x.e.start_time_s.toFixed(2)}–${x.e.end_time_exclusive_s.toFixed(2)} s · Track ${x.tid} · ${metres(x.e.peak_margin_m)} · Review`;b.onclick=()=>selectEvent(x);$('events').append(b);}
if(!events.length)$('events').textContent=c.result?'No candidates observed. This does not prove that the clip is clear.':'Run analysis to populate the review queue.';$('selected').textContent='Select a candidate first';$('notes').value='';$('saved').textContent='';toggleDecisions(false);list();drawTimeline();}
function selectEvent(x){selected=x;video.pause();video.currentTime=Math.max(0,x.e.start_time_s-1);$('selected').textContent=`Track ${x.tid}, ${x.e.start_time_s.toFixed(2)} s`;$('saved').textContent='';$('notes').value='';toggleDecisions(true);drawTimeline();}
function toggleDecisions(on){document.querySelectorAll('[data-decision]').forEach(b=>b.disabled=!on);}
function project(p){const h=clip.calibration.homography,z=h[2][0]*p[0]+h[2][1]*p[1]+h[2][2];if(Math.abs(z)<1e-9)return null;const uv=[(h[0][0]*p[0]+h[0][1]*p[1]+h[0][2])/z,(h[1][0]*p[0]+h[1][1]*p[1]+h[1][2])/z];return uv.every(Number.isFinite)?uv:null;}
function draw(now,metadata){if(clip){frameIndex=Math.max(0,Math.min(clip.frames-1,Math.floor(((metadata?.mediaTime)??video.currentTime)*clip.fps+1e-5)));$('frame').textContent=`Frame ${frameIndex} · ${clip.fps} fps`;canvas.width=video.videoWidth||640;canvas.height=video.videoHeight||360;ctx.clearRect(0,0,canvas.width,canvas.height);if($('showOverlay').checked)drawBoundary();const entries=Object.entries(clip.result?.tracks||{});let focus=null;
for(const [tid,t] of entries){const f=t.frames.find(f=>f.frame_idx===frameIndex);if(!f)continue;const uv=f.contacts_world.map(project).filter(Boolean);if(uv.length!==4)continue;if(!focus||selected?.tid===tid)focus={tid,t,f,uv};if($('showOverlay').checked){ctx.strokeStyle=f.geometry_status==='outside'?'#ff667a':'#f3c76c';ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=2;for(const [x,y]of uv){ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.stroke();}const centre=uv.reduce((a,b)=>[a[0]+b[0]/4,a[1]+b[1]/4],[0,0]);ctx.font='14px sans-serif';ctx.fillText(`Track ${tid} · ${metres(f.margin_m)}`,centre[0],centre[1]-20);}}
const crop=$('crop'),cc=crop.getContext('2d');cc.clearRect(0,0,crop.width,crop.height);if(focus){const {tid,t,f,uv}=focus;const xs=uv.map(p=>p[0]),ys=uv.map(p=>p[1]);const x=Math.max(0,Math.min(...xs)-30),y=Math.max(0,Math.min(...ys)-40);const w=Math.min(video.videoWidth-x,Math.max(...xs)-x+30),h=Math.min(video.videoHeight-y,Math.max(...ys)-y+40);if(w>0&&h>0&&video.readyState>=2){const scale=Math.min(crop.width/w,crop.height/h);cc.drawImage(video,x,y,w,h,(crop.width-w*scale)/2,(crop.height-h*scale)/2,w*scale,h*scale);}
const interval=f.margin_interval_m;$('details').textContent=`Track ${tid} | Estimated margin ${metres(f.margin_m)}. ${interval?'Model-based range: '+metres(interval[0])+' to '+metres(interval[1])+'. ':''}Detection score: ${percent(f.score)}. Identity score: ${percent(t.attribution?.confidence)}. Geometry: ${f.geometry_status||'not assessed'}.`;$('identity').textContent=t.attribution?.car_id||'Unverified';}else{$('details').textContent=clip.result?'No tracked geometry on this original frame. Evidence is missing.':'No inference results. The original video can still be inspected.';$('identity').textContent='Unverified';}}
if(video.requestVideoFrameCallback&&!metadata?.manual)video.requestVideoFrameCallback(draw);}
function drawTimeline(){const c=$('timeline'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);g.strokeStyle='#f3c76c';g.beginPath();g.moveTo(0,50);g.lineTo(c.width,50);g.stroke();for(const [tid,t] of Object.entries(clip?.result?.tracks||{})){if(selected&&selected.tid!==tid)continue;let previous=null;for(const f of t.frames){const x=f.frame_idx/Math.max(clip.frames-1,1)*c.width,y=50-Math.max(-1,Math.min(1,f.margin_m))*42;if(f.margin_interval_m){g.fillStyle='#67e7d020';const a=50-Math.max(-1,Math.min(1,f.margin_interval_m[1]))*42,b=50-Math.max(-1,Math.min(1,f.margin_interval_m[0]))*42;g.fillRect(x,a,Math.max(1,c.width/clip.frames),b-a);}if(previous&&f.frame_idx===previous.i+1){g.strokeStyle='#67e7d0';g.beginPath();g.moveTo(previous.x,previous.y);g.lineTo(x,y);g.stroke();}previous={i:f.frame_idx,x,y};}}}
$('prev').onclick=()=>{video.pause();video.currentTime=Math.max(0,(frameIndex-1+.1)/clip.fps);};$('next').onclick=()=>{video.pause();video.currentTime=Math.min((clip.frames-1+.1)/clip.fps,(frameIndex+1+.1)/clip.fps);};$('speed').onchange=()=>video.playbackRate=Number($('speed').value);$('filter').onchange=list;$('showOverlay').onchange=()=>draw(null,{mediaTime:video.currentTime,manual:true});
video.addEventListener('error',()=>$('error').textContent='Video could not be opened. Serve this bundle through the documented local HTTP command.');
for(const b of document.querySelectorAll('[data-decision]'))b.onclick=()=>{if(!selected)return;const entry={clip_id:clip.id,video_sha256:clip.video_sha256,track_id:selected.tid,event_index:selected.index,start_frame:selected.e.start_frame,end_frame:selected.e.end_frame_inclusive,decision:b.dataset.decision,notes:$('notes').value,reviewed_at:new Date().toISOString()};reviews.push(entry);try{localStorage.setItem('vmax-review-log-v1',JSON.stringify(reviews));$('saved').textContent='Decision saved in this browser.';}catch(e){$('saved').textContent='Browser storage unavailable. Export the review log now.';}};
$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(reviews,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='vmax-review-log.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
if(video.requestVideoFrameCallback)video.requestVideoFrameCallback(draw);else video.addEventListener('timeupdate',()=>draw());video.addEventListener('loadeddata',()=>{if(!video.requestVideoFrameCallback)draw();});list();if(data.clips.length)choose(data.clips[0]);

function drawBoundary(){let lines=[];if(clip.track_polygon_m){lines=[[...clip.track_polygon_m,clip.track_polygon_m[0]]];}else if(!clip.result||clip.result.geometry_contract){for(const side of [-1,1]){const line=[];for(let i=0;i<=120;i++){const s=-30+i*(Math.PI*20+60)/120,a=Math.max(0,Math.min(Math.PI*20,s))/40;line.push([40*Math.sin(a)+Math.min(s,0)-side*7*Math.sin(a),40*(1-Math.cos(a))+Math.max(s-Math.PI*20,0)+side*7*Math.cos(a)]);}lines.push(line);}}ctx.strokeStyle='#f3c76c';ctx.lineWidth=1.5;for(const line of lines){let live=false;ctx.beginPath();for(const p of line){const uv=project(p);if(!uv||uv.some(v=>Math.abs(v)>20000)){live=false;continue;}if(live)ctx.lineTo(...uv);else ctx.moveTo(...uv);live=true;}ctx.stroke();}}
